### ISSUE TITLE
wai-session-0.3 does not compile

### ISSUE THREAD

**Issue by peti** [singpolyma/wai-session#5]
Citing from http://hydra.cryp.to/build/623839/nixlog/1/raw:

    Network/Wai/Session/Map.hs:50:28:
        Expecting one more argument to ‘HasGetter sv’
        Expected a constraint,
          but ‘HasGetter sv’ has kind ‘* -> Constraint’
        In the type signature for ‘sessionFromMapStateVar’:
          sessionFromMapStateVar :: (HasGetter sv,
                                     HasSetter sv,
                                     Ord k,
                                     MonadIO m) =>
                                    sv (Map k v) -> Session m k v

My guess is that the code can't deal with recent versions of `lens`.

**Comment by creichert** [comment]
This was fixed in the last few commits and hasn't been released to hackage yet.

https://github.com/singpolyma/wai-session/issues/4

**Comment by singpolyma** [comment]
Thanks for the bump!  I forgot to release.  It's on hackage now as 0.3.1
