### ISSUE TITLE
Example does not compile

### ISSUE THREAD

**Issue by dbushenko** [singpolyma/wai-session#6]
Firstly you need to change import qualified Data.Vault as Vault to import qualified Data.Vault.Lazy as Vault. But after all it still can't compile with the following message:

src/Main.hs:51:9:
    Couldn't match type `ResourceT IO Response'
                  with `(Response -> IO ResponseReceived) -> IO ResponseReceived'
    Expected type: ResourceT IO (Maybe String)
                   -> (Maybe String -> ResourceT IO Response)
                   -> (Response -> IO ResponseReceived)
                   -> IO ResponseReceived
      Actual type: ResourceT IO (Maybe String)
                   -> (Maybe String -> ResourceT IO Response) -> ResourceT IO Response
    In a stmt of a 'do' block: u <- sessionLookup "u"
    In the expression:
      do { u <- sessionLookup "u";
           sessionInsert "u" insertThis;
           return
           $ responseLBS ok200 []
             $ maybe (fromString "Nothing") fromString u }
    In an equation for `app':
        app session env
          = do { u <- sessionLookup "u";
                 sessionInsert "u" insertThis;
                 return
                 $ responseLBS ok200 []
                   $ maybe (fromString "Nothing") fromString u }
          where
              insertThis = show $ pathInfo env
              Just (sessionLookup, sessionInsert)
                = Vault.lookup session (vault env)

**Comment by singpolyma** [comment]
This is because the example was written for older WAI.  I have updated the example to be for newest WAI, so this should be fixed by 713119324f2a42c3225ae6f9209483591adaaf36
