### ISSUE TITLE
Why is `Network.Wai.Session.Map` so strangely designed?

### ISSUE THREAD

**Issue by athanclark** [singpolyma/wai-session#9]
I've been looking at your module, making a different implementation with STM and HashPSQ, but have run into something... weird. If the cache is a `StateVar` of a `Map` from a unique Id to some value, but on [line 31](https://github.com/singpolyma/wai-session/blob/master/Network/Wai/Session/Map.hs#L31), you're using the result in another peek - the result should be an infinite type somehow, `Fix (\x -> Map k (StateVars x))`.

Is there another way this should be working? For instance, using `ssv` instead of `sv`, at the reference site?

**Comment by singpolyma** [comment]
`ssv` is `StateVar (Map UniqueId (StateVar (Map k v)))` so there are two maps and two statevars.  The outer statevar/map is session id to session, and the inner statevar/map is the key/values stored in a given session.  Check out wai-session-tokyocabinet and wai-session-clientsession as well for more examples of backends.
